# Generated by Django 3.2 on 2021-05-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.AddField(
            model_name='game',
            name='gametype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gametype'),
            preserve_default=False,
        ),
    ]
