# Generated by Django 3.2 on 2021-05-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_auto_20210507_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gametype',
            new_name='game_type',
        ),
    ]
